import type { Token, SmartMoneyAlert, GraduatingToken, NarrativeStat } from '@/types';

/**
 * Mock data for development.
 * When the ingestion worker is live, swap this for real fetches/WebSocket.
 */

const now = Date.now();

export const MOCK_TOKENS: Token[] = [
  {
    mintAddress: '8x2KmPnQRsTuvWxYz1A2B3C4D5E6F7G8H9I0JkLmNo',
    name: 'Autonomous General Intel',
    symbol: 'AGI',
    imageUrl: null,
    creatorWallet: '7Hx9K2pLmN3oPqR4sTuVwXyZ1A2B3C4D5E6F7G8H',
    createdAt: new Date(now - 12_000).toISOString(),
    graduatedAt: null,
    isComplete: false,
    category: 'AI',
    subcategory: 'AGI',
    keywords: ['agi', 'ai', 'agent'] as const,
    riskScore: 12,
    riskLevel: 'low',
    marketCapUsd: 48_200,
    priceSol: 0.000_000_026,
    holdersCount: 47,
    bondingCurveProgress: 0.52,
    volume24hUsd: 24_800,
    devHoldingPct: 3.2,
    buys1h: 82,
    sells1h: 12,
    hasSmartMoney: true,
    isFresh: true,
  },
  {
    mintAddress: 'PNuT2k9pL3mNoPqR4sTuVwXyZ1A2B3C4D5E6F7G8',
    name: 'Peanut the Squirrel',
    symbol: 'PNUT',
    imageUrl: null,
    creatorWallet: '4Yt8nKpLmN3oPqR4sTuVwXyZ1A2B3C4D5E6F7G8H',
    createdAt: new Date(now - 34_000).toISOString(),
    graduatedAt: null,
    isComplete: false,
    category: 'Animal',
    subcategory: 'Squirrel',
    keywords: ['animal', 'meme', 'pnut'] as const,
    riskScore: 38,
    riskLevel: 'medium',
    marketCapUsd: 24_800,
    priceSol: 0.000_000_013,
    holdersCount: 28,
    bondingCurveProgress: 0.18,
    volume24hUsd: 12_400,
    devHoldingPct: 4.8,
    buys1h: 42,
    sells1h: 8,
    hasSmartMoney: false,
    isFresh: true,
  },
  {
    mintAddress: 'TR28cMpLmN3oPqR4sTuVwXyZ1A2B3C4D5E6F7G8H',
    name: 'Trump 2028 Coin',
    symbol: 'TRUMP28',
    imageUrl: null,
    creatorWallet: '9F2k8mQpRsTuvWxYz1A2B3C4D5E6F7G8H9I0JkLm',
    createdAt: new Date(now - 102_000).toISOString(),
    graduatedAt: null,
    isComplete: false,
    category: 'Political',
    subcategory: 'Trump',
    keywords: ['trump', 'political', '2028'] as const,
    riskScore: 18,
    riskLevel: 'low',
    marketCapUsd: 182_000,
    priceSol: 0.000_000_096,
    holdersCount: 214,
    bondingCurveProgress: 0.64,
    volume24hUsd: 89_400,
    devHoldingPct: 2.1,
    buys1h: 312,
    sells1h: 48,
    hasSmartMoney: true,
    isFresh: false,
  },
  {
    mintAddress: 'NNcAtMpLmN3oPqR4sTuVwXyZ1A2B3C4D5E6F7G8H',
    name: 'Neural Net Cat',
    symbol: 'NNCAT',
    imageUrl: null,
    creatorWallet: '2HpQkLm9pLmN3oPqR4sTuVwXyZ1A2B3C4D5E6F7G',
    createdAt: new Date(now - 128_000).toISOString(),
    graduatedAt: null,
    isComplete: false,
    category: 'AI',
    subcategory: 'Cat',
    keywords: ['ai', 'cat', 'neural'] as const,
    riskScore: 72,
    riskLevel: 'high',
    marketCapUsd: 8_400,
    priceSol: 0.000_000_004,
    holdersCount: 12,
    bondingCurveProgress: 0.06,
    volume24hUsd: 3_200,
    devHoldingPct: 12.4,
    buys1h: 18,
    sells1h: 3,
    hasSmartMoney: false,
    isFresh: false,
  },
  {
    mintAddress: 'DGmAfIaMpLmN3oPqR4sTuVwXyZ1A2B3C4D5E6F7G',
    name: 'Doge Mafia',
    symbol: 'DGMAFIA',
    imageUrl: null,
    creatorWallet: '6Yt8nKpLmN3oPqR4sTuVwXyZ1A2B3C4D5E6F7G8H',
    createdAt: new Date(now - 262_000).toISOString(),
    graduatedAt: null,
    isComplete: false,
    category: 'Animal',
    subcategory: 'Dog',
    keywords: ['dog', 'doge', 'meme'] as const,
    riskScore: 42,
    riskLevel: 'medium',
    marketCapUsd: 34_700,
    priceSol: 0.000_000_018,
    holdersCount: 68,
    bondingCurveProgress: 0.32,
    volume24hUsd: 18_900,
    devHoldingPct: 5.8,
    buys1h: 94,
    sells1h: 31,
    hasSmartMoney: false,
    isFresh: false,
  },
  {
    mintAddress: 'AGENT0MpLmN3oPqR4sTuVwXyZ1A2B3C4D5E6F7G8',
    name: 'Agent Zero',
    symbol: 'AGENT0',
    imageUrl: null,
    creatorWallet: '8Mn4pK7vRsTuvWxYz1A2B3C4D5E6F7G8H9I0JkLm',
    createdAt: new Date(now - 314_000).toISOString(),
    graduatedAt: null,
    isComplete: false,
    category: 'AI',
    subcategory: 'AI Agent',
    keywords: ['ai', 'agent', 'autonomous'] as const,
    riskScore: 15,
    riskLevel: 'low',
    marketCapUsd: 284_000,
    priceSol: 0.000_000_148,
    holdersCount: 312,
    bondingCurveProgress: 0.82,
    volume24hUsd: 142_000,
    devHoldingPct: 1.4,
    buys1h: 487,
    sells1h: 92,
    hasSmartMoney: true,
    isFresh: false,
  },
];

export const MOCK_ALERTS: SmartMoneyAlert[] = [
  {
    id: 'alert-001',
    type: 'smart_money_cluster',
    mintAddress: '8x2KmPnQRsTuvWxYz1A2B3C4D5E6F7G8H9I0JkLmNo',
    symbol: 'AGI',
    message: '5 smart wallets bought in last 60s · $48K avg buy',
    walletCount: 5,
    totalSolVolume: 24,
    createdAt: new Date(now - 12_000).toISOString(),
  },
  {
    id: 'alert-002',
    type: 'kol_entry',
    mintAddress: 'AGENT0MpLmN3oPqR4sTuVwXyZ1A2B3C4D5E6F7G8',
    symbol: 'AGENT0',
    message: 'orbital.sol (94% WR) entered · $8K position',
    walletCount: 1,
    totalSolVolume: 8,
    createdAt: new Date(now - 120_000).toISOString(),
  },
  {
    id: 'alert-003',
    type: 'smart_money_cluster',
    mintAddress: 'TR28cMpLmN3oPqR4sTuVwXyZ1A2B3C4D5E6F7G8H',
    symbol: 'TRUMP28',
    message: '3 KOL wallets cluster · +$24K combined',
    walletCount: 3,
    totalSolVolume: 12,
    createdAt: new Date(now - 240_000).toISOString(),
  },
];

export const MOCK_GRADUATING: GraduatingToken[] = [
  { mintAddress: 'AGENT0MpLmN3oPqR4sTuVwXyZ1A2B3C4D5E6F7G8', symbol: 'AGENT0', progress: 0.82 },
  { mintAddress: 'TR28cMpLmN3oPqR4sTuVwXyZ1A2B3C4D5E6F7G8H', symbol: 'TRUMP28', progress: 0.64 },
  { mintAddress: '8x2KmPnQRsTuvWxYz1A2B3C4D5E6F7G8H9I0JkLmNo', symbol: 'AGI', progress: 0.52 },
];

export const MOCK_NARRATIVES: NarrativeStat[] = [
  { category: 'AI', count: 1054, percentage: 37, colorVar: '#4dabff' },
  { category: 'Animal', count: 626, percentage: 22, colorVar: '#ffb547' },
  { category: 'Meme', count: 541, percentage: 19, colorVar: '#ff6bcb' },
  { category: 'Political', count: 313, percentage: 11, colorVar: '#ff3d5a' },
  { category: 'Celebrity', count: 171, percentage: 6, colorVar: '#b87cff' },
  { category: 'Other', count: 142, percentage: 5, colorVar: '#8a929c' },
];
